### ISSUE TITLE
Information Request:  Spurious Transmissions

### ISSUE THREAD

**Issue by john-** [madengr/ham2mon#24]
I mostly listen to NBFM with ham2mon.   For things like transmission in my local area it works great.   However, I also use it at automobile races that have heavy radio traffic with varying degrees of signal strength.

What I see in this case is there are times where not only is the expected signal received but "duplicates" across other frequencies.   These duplicates tend to lower quality and can be mixed with signals on those other frequencies.

This may be a question of adjusting the gain based on my location.   However, I am using ham2mon in a mobile way (on a golf cart over 640 acres of area).

Currently I am using an RTL based receiver and played around with hardware AGC.   This didn't appear to help.

Are there any options to address this?   It seems like this is a fundamental issue so I must be missing something basic.

Thanks,

Jon

**Comment by Reid-n0rc** [comment]
It's definitely a hardware issue. Are you using the shielded version from rtl-sdr.com (sold on Amazon)? The good and bad of rtl based receivers is that they're cheap. They cut corners where they could.

I would also suggest putting a bandpass filter for for the frequencies of interest on the front end as well.

**Comment by john-** [comment]
I am using the ones Noolec modifies...although I don't think shielding is part of the modifications though.   I can compare it to a hackrf to see how much that changes things.

I have a band reject filter for wide band FM.  I will take a look at band pass for the frequencies of interest.   Is the idea that with a lower noise floor I can decrease the receiver gain?   Or is there a different reason?

**Comment by madengr** [comment]
Yeah, I agree with Reid.  Sounds like you may be getting intermods with other channels.   3rd order IMD will reduce 9 dB for every 3 dB reduction in gain, so it does not take much to improve it  I don't recall how many gain stages the RTL has, but start with the last one, and tweak them each 3 dB, to see which one gives the best improvement, and which stage it is coming from.

It could be a strong signal at an LO harmonic causing it, so look for strong signals at N * LO.  Even the AD9364 used in $1k radios has piss poor harmonic rejection, which is troublesome at the amateur 2 meter band since 5 * 144 = 720 MHz, which is a nation wide LTE carrier that is super strong.  Even non harmonically related signals could overflow the ADC or a host of other effects.

Do a wideband survey of the area using GQRX and look for any strong signals.  Especially stuff line of sight; pager, land mobile, etc.  I'm sure a race track is loaded with that stuff.  If you are not sure if something is real, twiddle the gain and see if it drops proportionally.
 
Really no way around it other than traditional filtering.  You may even need an attenuator on the front end.

**Comment by john-** [comment]
Thanks for the great information.   Clearly I need to focus on the front end so closing this item.
